# docker-compose.yml
services:
  web:
    container_name: cv_scanner-web
    build: .
    command: bash -c "
        python manage.py migrate
        && python /usr/src/app/manage.py runserver 0.0.0.0:8000 "
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: cv_scanner-db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: